[package]
name = "ascii-pack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
ascii-pack-macro = { path = "../ascii-pack-macro" }
ntest_timeout = "0.9.0"
thiserror = "1.0.50"
