[package]
name = "ascii-pack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
anyhow = "1.0.75"
ascii-pack-macro = { path = "../ascii-pack-macro" }
ntest_timeout = "0.9.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
