on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v3
      - name: "Cargo Test"
        uses: Kristories/cargo-test@v1.0.0
        with:
          manifest-path: './ascii-pack-macroCargo.toml'